### Importación de datos

In [16]:
import pandas as pd

url = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_1%20.csv"
url2 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_2.csv"
url3 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_3.csv"
url4 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_4.csv"

tienda = pd.read_csv(url)
tienda2 = pd.read_csv(url2)
tienda3 = pd.read_csv(url3)
tienda4 = pd.read_csv(url4)

tienda.head(15)

,Producto,Categoría del Producto,Precio,Costo de envío,Fecha de Compra,Vendedor,Lugar de Compra,Calificación,Método de pago,Cantidad de cuotas,lat,lon
0,Asistente virtual,Electrónicos,164300.0,6900.0,16/01/2021,Pedro Gomez,Bogotá,4,Tarjeta de crédito,8,4.60971,-74.08175
1,Mesa de comedor,Muebles,192300.0,8400.0,18/05/2022,Beatriz Morales,Medellín,1,Tarjeta de crédito,4,6.25184,-75.56359
2,Juego de mesa,Juguetes,209600.0,15900.0,15/03/2021,Juan Fernandez,Cartagena,1,Tarjeta de crédito,1,10.39972,-75.51444
3,Microondas,Electrodomésticos,757500.0,41000.0,03/05/2022,Juan Fernandez,Cali,4,Nequi,1,3.43722,-76.52250
4,Silla de oficina,Muebles,335200.0,20200.0,07/11/2020,Maria Alfonso,Medellín,5,Nequi,1,6.25184,-75.56359
5,Bloques de construcción,Juguetes,24200.0,0.0,03/12/2020,Beatriz Morales,Cali,5,Cupón,1,3.43722,-76.52250
6,Muñeca bebé,Juguetes,44200.0,0.0,07/08/2021,Juan Fernandez,Bogotá,3,Nequi,1,4.60971,-74.08175
7,Lavavajillas,Electrodomésticos,1189700.0,63700.0,18/06/2021,Felipe Santos,Santa Marta,5,Tarjeta de crédito,10,11.24079,-74.19904
8,Lavadora de ropa,Electrodomésticos,1518200.0,79000.0,08/01/2022,Izabela de León,Bogotá,1,Tarjeta de crédito,5,4.60971,-74.08175
9,Carrito de control remoto,Juguetes,75200.0,5100.0,24/02/2020,Beatriz Morales,Bogotá,5,Nequi,1,4.60971,-74.08175
10,Refrigerador,Electrodomésticos,2431300.0,127600.0,03/04/2020,Blanca Ramirez,Bogotá,5,Tarjeta de crédito,2,4.60971,-74.08175
11,Lavavajillas,Electrodomésticos,1417100.0,75700.0,05/07/2021,Rafael Acosta,Cartagena,5,Tarjeta de crédito,1,10.39972,-75.51444
12,Auriculares,Electrónicos,91800.0,5300.0,20/02/2020,Rafael Acosta,Medellín,1,Tarjeta de crédito,5,6.25184,-75.56359
13,Olla de presión,Artículos para el hogar,66700.0,1700.0,10/09/2020,Izabela de León,Pereira,4,Tarjeta de crédito,2,4.81333,-75.69611
14,Bicicleta,Deportes y diversión,613300.0,30800.0,04/09/2020,Juan Fernandez,Bogotá,2,Tarjeta de crédito,8,4.60971,-74.08175

#1. Análisis de facturación

In [ ]:
def facturacion_total(tienda):
  suma=0
  for i in range(len(tienda)):
    precio = tienda.loc[i,'Precio'] #loc.[indice_fila,'nombre columna'] loc.=location
    suma += precio
  return suma

print(f'TOTAL FACTURACION TIENDA 1 : ${facturacion_total(tienda)} .-')
print(f'TOTAL FACTURACION TIENDA 2 : ${facturacion_total(tienda2)} .-')
print(f'TOTAL FACTURACION TIENDA 1 : ${facturacion_total(tienda3)} .-')
print(f'TOTAL FACTURACION TIENDA 1 : ${facturacion_total(tienda4)} .-')

TOTAL FACTURACION TIENDA 1 : $1150880400.0 .-
TOTAL FACTURACION TIENDA 2 : $1116343500.0 .-
TOTAL FACTURACION TIENDA 1 : $1098019600.0 .-
TOTAL FACTURACION TIENDA 1 : $1038375700.0 .-

In [ ]:
def resumen_ingresos(tiendas):
    resultados = {}
    for i, tienda in enumerate(tiendas, start=1):
        nombre = f"Tienda {i}"
        total = float(facturacion_total(tienda))
        resultados[nombre] = total
    return resultados

lista_tiendas=[tienda,tienda2,tienda3,tienda4]
resumen= resumen_ingresos(lista_tiendas)
print(resumen)

{'Tienda 1': 1150880400.0, 'Tienda 2': 1116343500.0, 'Tienda 3': 1098019600.0, 'Tienda 4': 1038375700.0}

# 2. Ventas por categoría

In [ ]:
#cantidad de productos vendidos por categoria de cada tienda

In [ ]:
def prod_vendidos_por_categoria(tienda):
  categorias = {}
  for i in range(len(tienda)):
    categoria_producto = tienda.loc[i,"Categoría del Producto"]
    if categoria_producto in categorias:
      categorias[categoria_producto] +=1
    else :
      categorias[categoria_producto] = 1

  return categorias

def listardict(tienda):
  for categoria, cantidad in prod_vendidos_por_categoria(tienda).items():
      print(f'\t {categoria}: {cantidad}')

print('TIENDA 1:')
listardict(tienda)
print('----------------------------------')
print('TIENDA 2:')
listardict(tienda2)
print('----------------------------------')
print('TIENDA 3:')
listardict(tienda3)
print('----------------------------------')
print('TIENDA 4:')
listardict(tienda4)

TIENDA 1:
	 Electrónicos: 448
	 Muebles: 465
	 Juguetes: 324
	 Electrodomésticos: 312
	 Artículos para el hogar: 171
	 Deportes y diversión: 284
	 Libros: 173
	 Instrumentos musicales: 182
----------------------------------
TIENDA 2:
	 Muebles: 442
	 Instrumentos musicales: 224
	 Deportes y diversión: 275
	 Electrónicos: 422
	 Artículos para el hogar: 181
	 Juguetes: 313
	 Electrodomésticos: 305
	 Libros: 197
----------------------------------
TIENDA 3:
	 Electrodomésticos: 278
	 Muebles: 499
	 Instrumentos musicales: 177
	 Deportes y diversión: 277
	 Electrónicos: 451
	 Juguetes: 315
	 Artículos para el hogar: 177
	 Libros: 185
----------------------------------
TIENDA 4:
	 Electrodomésticos: 254
	 Muebles: 480
	 Deportes y diversión: 277
	 Libros: 187
	 Electrónicos: 451
	 Instrumentos musicales: 170
	 Juguetes: 338
	 Artículos para el hogar: 201

# 3. Calificación promedio de la tienda

In [6]:
def calificacion_promedio_por_tienda(tienda):
  suma= 0
  cont = 0
  promedio = 0
  for i in range(len(tienda)):
    suma += tienda.loc[i,"Calificación"]
    cont += 1
  promedio = suma/cont
  return promedio

print(f"CALIFICACION TIENDA 1 : {calificacion_promedio_por_tienda(tienda)}")
print()
print(f"CALIFICACION TIENDA 2 : {calificacion_promedio_por_tienda(tienda2)}")
print()
print(f"CALIFICACION TIENDA 3 : {calificacion_promedio_por_tienda(tienda3)}")
print()
print(f"CALIFICACION TIENDA 4 : {calificacion_promedio_por_tienda(tienda4)}")

CALIFICACION TIENDA 1 : 3.976685036032217

CALIFICACION TIENDA 2 : 4.037303942348453

CALIFICACION TIENDA 3 : 4.048325561678677

CALIFICACION TIENDA 4 : 3.9957591178965224

# 4. Productos más y menos vendidos

In [ ]:
#por tienda y en todas las sucursales
#5 productos mas vendidos y 5 menos vendidos: mostrar nombre de producto, cantidad de unidades vendidas, precio unitario y total ventas
#para esto: identificar producto que se repite mas veces

In [24]:
def ventas_productos_unidad(tienda):

    cantidad_ventas = tienda["Producto"].value_counts()
    suma_ventas_producto = tienda.groupby("Producto")["Precio"].sum()
    ventas = cantidad_ventas.reset_index()
    ventas.columns = ["PRODUCTO", "CANTIDAD DE VENTAS"]
    ventas["TOTAL"] = ventas["PRODUCTO"].map(suma_ventas_producto)

    ventas_ordenado = ventas.sort_values(by="CANTIDAD DE VENTAS", ascending=False)

    return ventas_ordenado

def ventas_productos_precio(tienda):
  cantidad_ventas = tienda["Producto"].value_counts()
  suma_ventas_producto = tienda.groupby("Producto")["Precio"].sum()
  ventas = cantidad_ventas.reset_index()
  ventas.columns = ["PRODUCTO", "CANTIDAD DE VENTAS"]
  ventas["TOTAL"] = ventas["PRODUCTO"].map(suma_ventas_producto)

  ventas_ordenado = ventas.sort_values(by="TOTAL", ascending=False)

  return ventas_ordenado


def mas_vendidos(lista_productos):
  return lista_productos.head(5)

def menos_vendidos(lista_productos):
  return lista_productos.tail(5)

def ranking_por_tienda(tienda):
  lista_productos_unidad = ventas_productos_unidad(tienda)
  lista_productos_precio = ventas_productos_precio(tienda)
  mas_vendidos_unidad=mas_vendidos(lista_productos_unidad)
  menos_vendidos_unidad=menos_vendidos(lista_productos_unidad)
  mas_vendidos_precio = mas_vendidos(lista_productos_precio)
  menos_vendidos_precio = menos_vendidos(lista_productos_precio)

  print("_________VENTAS POR UNIDAD_________")
  print("MAS VENTAS POR UNIDAD")
  print(mas_vendidos_unidad)
  print("MENOS VENTAS POR UNIDAD")
  print(menos_vendidos_unidad)

  print("_________VENTAS POR PRECIO_________")
  print("MAS VENTAS POR PRECIO")
  print(mas_vendidos_precio)
  print("MENOS VENTAS POR PRECIO")
  print(menos_vendidos_precio)

#ranking_por_tienda(tienda)

lista_todas_las_sucursales = pd.concat([tienda, tienda2, tienda3, tienda4], ignore_index=True)

ranking_por_tienda(lista_todas_las_sucursales)

_________VENTAS POR UNIDAD_________
MAS VENTAS POR UNIDAD
                    PRODUCTO  CANTIDAD DE VENTAS        TOTAL
0              Mesa de noche                 210   58419500.0
1  Carrito de control remoto                 206   14767700.0
2                 Microondas                 206  115699500.0
3                    Batería                 203  147806300.0
4                  Cama king                 201  135780400.0
MENOS VENTAS POR UNIDAD
                       PRODUCTO  CANTIDAD DE VENTAS        TOTAL
46  Ciencia de datos con Python                 166    9036100.0
47           Guitarra eléctrica                 165  129404800.0
48                      Mochila                 163   16065700.0
49    Auriculares con micrófono                 158   22748500.0
50                 Celular ABXY                 157  157911100.0
_________VENTAS POR PRECIO_________
MAS VENTAS POR PRECIO
            PRODUCTO  CANTIDAD DE VENTAS        TOTAL
25     TV LED UHD 4K                 187  432489600.0
10         Iphone 15                 198  401051200.0
17      Refrigerador                 191  384937400.0
16          Smart TV                 192  290221800.0
35  Lavadora de ropa                 176  242468600.0
MENOS VENTAS POR PRECIO
              PRODUCTO  CANTIDAD DE VENTAS      TOTAL
43        Set de vasos                 169  5584200.0
33   Ajedrez de madera                 180  5149100.0
38      Dinosaurio Rex                 175  3112900.0
26  Cuerda para saltar                 186  3068300.0
32     Cubo mágico 8x8                 180  2729300.0

# 5. Envío promedio por tienda

In [31]:
def envio_promedio(tienda):
  promedio = tienda["Costo de envío"].mean().round(3)

  return promedio

print(f"COSTO DE ENVIOS PROMEDIO TIENDA 1 {envio_promedio(tienda)}")
print(f"COSTO DE ENVIOS PROMEDIO TIENDA 2 {envio_promedio(tienda2)}")
print(f"COSTO DE ENVIOS PROMEDIO TIENDA 3 {envio_promedio(tienda3)}")
print(f"COSTO DE ENVIOS PROMEDIO TIENDA 4 {envio_promedio(tienda4)}")

COSTO DE ENVIOS PROMEDIO TIENDA 1 26018.61
COSTO DE ENVIOS PROMEDIO TIENDA 2 25216.236
COSTO DE ENVIOS PROMEDIO TIENDA 3 24805.68
COSTO DE ENVIOS PROMEDIO TIENDA 4 23459.457